version: "3.9"
services:
  mysql:
    container_name: mysql-mel
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'mel-db'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
    expose:
      - '3306'